# Generated by Django 4.2.11 on 2024-04-12 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asignaturas',
            fields=[
                ('id_asignatura', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('codigo_curso', models.CharField(max_length=7)),
            ],
            options={
                'verbose_name': 'Asignatura',
                'verbose_name_plural': 'Asignaturas',
            },
        ),
        migrations.CreateModel(
            name='Etiquetas',
            fields=[
                ('id_etiqueta', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=15)),
            ],
            options={
                'verbose_name': 'Etiqueta',
                'verbose_name_plural': 'Etiquetas',
            },
        ),
        migrations.CreateModel(
            name='TiposMaterial',
            fields=[
                ('id_tipo_material', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Tipo de Material',
                'verbose_name_plural': 'Tipos de Material',
            },
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('apellido', models.CharField(max_length=20)),
                ('correo', models.EmailField(max_length=254)),
                ('contrasena', models.CharField(max_length=15)),
                ('fecha_nacimiento', models.DateField()),
                ('fecha_ingreso', models.DateField()),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
            },
        ),
        migrations.CreateModel(
            name='Semestres',
            fields=[
                ('id_semestre', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('asignatura', models.ManyToManyField(to='catalog.asignaturas')),
            ],
            options={
                'verbose_name': 'Semestre',
                'verbose_name_plural': 'Semestres',
            },
        ),
        migrations.CreateModel(
            name='Profesores',
            fields=[
                ('id_profesor', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('apellido', models.CharField(max_length=20)),
                ('asignatura', models.ManyToManyField(to='catalog.asignaturas')),
            ],
            options={
                'verbose_name': 'Profesor',
                'verbose_name_plural': 'Profesores',
            },
        ),
        migrations.CreateModel(
            name='Documentos',
            fields=[
                ('id_documento', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=15)),
                ('fecha_subida', models.DateField()),
                ('archivo', models.FileField(upload_to='pdf/')),
                ('calificacion', models.FloatField()),
                ('cantidad_descargas', models.IntegerField()),
                ('etiquetas', models.ManyToManyField(to='catalog.etiquetas')),
                ('id_asignaturas', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.asignaturas')),
                ('id_tipo_material', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.tiposmaterial')),
                ('id_usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.usuarios')),
                ('profesor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.profesores')),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
            },
        ),
        migrations.CreateModel(
            name='Comentarios',
            fields=[
                ('id_comentario', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('contenido', models.TextField()),
                ('id_documento_asociado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.documentos')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.usuarios')),
            ],
            options={
                'verbose_name': 'Comentario',
                'verbose_name_plural': 'Comentarios',
            },
        ),
    ]
