# Generated by Django 4.2.11 on 2024-06-01 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentos',
            name='calificaciones_usuarios',
            field=models.JSONField(default=dict),
        ),
    ]
