# Generated by Django 4.2.11 on 2024-04-25 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_documentos_archivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentos',
            name='miniatura',
            field=models.ImageField(blank=True, null=True, upload_to='thumbnails/'),
        ),
    ]
