# Generated by Django 4.2.11 on 2024-06-03 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_documentos_calificaciones_usuarios'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='favoritos',
            field=models.ManyToManyField(blank=True, null=True, to='catalog.documentos'),
        ),
    ]
