# Generated by Django 4.2.11 on 2024-06-11 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_account_favoritos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etiquetas',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
    ]
