# Generated by Django 4.2.11 on 2024-04-30 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_remove_documentos_miniatura'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentos',
            name='titulo',
            field=models.CharField(max_length=50),
        ),
    ]
