# Generated by Django 4.2.11 on 2024-05-08 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_alter_documentos_titulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentos',
            name='num_calificaciones',
            field=models.IntegerField(default=0),
        ),
    ]
